apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-azure-files
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-files-example
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: files1
            mountPath: /tmp/files1
            readOnly: false
      volumes:
        - name: files1
          persistentVolumeClaim:
            claimName: azure-files-claim

